### ISSUE TITLE
Archive Directory

### ISSUE THREAD

**Issue by Sarci1** [ni/niveristand-embedded-data-logger-custom-device#3]
**Is your feature request related to a problem? Please describe.**
It would be ideal to have an archive directory to store the files that have been completed. This would provide clarity to other processes to be able to transfer those files to a host PC or other server for processing.

**Describe the solution you'd like**
A configuration that allows you to define the location of the archive.

**Describe alternatives you've considered**
A separate custom device that views all files in a specific directory and moves ones that are not the latest file.

**Additional context**

**Comment by rtzoeller** [comment]
Closed by https://github.com/ni/niveristand-embedded-data-logger-custom-device/pull/11.
