### ISSUE TITLE
No .tdms files start on trigger.

### ISSUE THREAD

**Issue by johndevera** [ni/niveristand-embedded-data-logger-custom-device#73]
**Describe the bug**
No .tdms files are generated after setting up EDL.
Does EDL work on Target running Linux x64?

**To Reproduce**
- Set up EDL with 5 channels
- Deploy
- Set log_trigger to 1

**Expected behavior**
Files should start appearing in folder and a new file should get created and previous file closed every 30sec.

**Screenshots**
Embedded Data Logger Config
<img width="966" alt="embedded_data_logger_config" src="https://github.com/ni/niveristand-embedded-data-logger-custom-device/assets/25378574/9228443a-39a7-4913-89ee-d74186d1a481">

Veristand Controller Specification
<img width="906" alt="controller_specification" src="https://github.com/ni/niveristand-embedded-data-logger-custom-device/assets/25378574/c5032e26-3371-4ca1-9720-7c40bee06acd">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Target OS: Linux x64
 - Veristand 2023 Q1

**Comment by jacobson3** [comment]
What are the status channels reading (the ones under data_log) when you're running this system definition? Also, is there anything relevant printed to the console?

I just set up a similar test with VeriStand 2023Q1 running on an 8861 running LinuxRT x64 and everything seemed to be working as expected. I copied all of the configurations in the images and just logged 5 random system channels. When I deployed the system definition I opened an SSH session and navigated to `/C/test_folder/stream_data` and just ran an `ls -l` to see that files were being created and data was being logged (I was really just looking at file size).

**Comment by Hongbo-Miao** [comment]
Thanks @jacobson3 ! I am working with @johndevera . Just confirm the log should be saved in host machine instead of target machine, right?
Another question, is there a link how to check this "Embedded Data Logger Custom Device" own log, just for debugging purpose, thanks! 😃

**Comment by jacobson3** [comment]
The log will be saved on the target LinuxRT system.

I'm not sure what you mean by "Embedded Data Logger Custom Device own log". Whatever VeriStand prints to the console during operation can also be read from `/dev/vcs`, maybe that's what  you're looking for.

**Comment by buckd** [comment]
> it automatically changes to home:\admin\stream

This bug is captured in #24. The custom device uses LabVIEW controls to construct the UI for configuration. LabVIEW path controls automatically convert paths to display valid paths on the current operating system. Because the configuration is running on Windows, the control converts what is entered to a LabVIEW path.

**Comment by jacobson3** [comment]
For question 2, `/dev/vcs` is probably where it prints errors. I don't think the custom device keeps a separate log so any errors should be passed back up to the VeriStand engine and end up in `/dev/vcs`.

You'll probably still want to look at the status channels as the custom device may be in a state where it won't log anything but it doesn't consider it an error.

**Comment by johndevera** [comment]
@jacobson3 @buckd thanks for your replies!

@jacobson3 Can you confirm, is your host machine running windows? Your first reply seems like the host machine is windows and target is linux. Also, this is our output of `/dev/vcs`

<img width="328" alt="image" src="https://github.com/ni/niveristand-embedded-data-logger-custom-device/assets/25378574/5c72b6cd-5122-4a17-80cf-7bd664f82ee3">

@buckd Is that just a UI bug? You mention in #24 that its "difficult". Does it in fact record files on the linux target when your host machine is windows?
We tried specifying the record folder on the linux system as `/home/admin/stream/` and we still did not see any .tdms.

**Comment by jacobson3** [comment]
Yes, the host is my Windows 10 laptop and the target is an 8861 running LinuxRT.

**Comment by rtzoeller** [comment]
> We tried specifying the record folder on the linux system as `/home/admin/stream/` and we still did not see any .tdms.

I think you're just hitting an unfortunate quirk at the intersection of how LabVIEW runs, the default users on NILRT, and Linux filesystem permissions. 

LabVIEW and therefore VeriStand run as `lvuser`, and can't write to `/home/admin` unless you modify the permissions. I'm not sure we do a good job reporting errors on this today. 

Can you try writing to `/home/lvuser/` instead?

**Comment by johndevera** [comment]
Thanks @rtzoeller I tried writing it to `/home/lvuser` but it didn't work. See how the path got entered in the EDL
<img width="677" alt="image" src="https://github.com/ni/niveristand-embedded-data-logger-custom-device/assets/25378574/3fe830a9-cee7-45f6-9d68-3541b0011e91">

**Comment by johndevera** [comment]
@jacobson3 @rtzoeller @buckd Thanks for your help!

The files are in fact at `/C/test_folder/stream_data`
Somehow when i viewed it before i didn't see the C folder. 

Closing this ticket.
I still think it would be better to specify a linux path if it is being save to ling.
